-- 1. CREACIÓN DE LA BASE DE DATOS
DROP DATABASE IF EXISTS LibreriaDB;
CREATE DATABASE LibreriaDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE LibreriaDB;

-- 2. CREACIÓN DE TABLAS

-- Tabla: GENERO
CREATE TABLE GENERO (
    ID_GENERO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_GENERO)
) ENGINE=InnoDB;

-- Tabla: AUTOR
CREATE TABLE AUTOR (
    ID_AUTOR INT NOT NULL AUTO_INCREMENT,
    NOMBRE_COMPLETO VARCHAR(255) NOT NULL,
    FECHA_NACIMIENTO DATE NULL,
    FECHA_FALLECIMIENTO DATE NULL,
    PRIMARY KEY (ID_AUTOR)
) ENGINE=InnoDB;

-- Tabla: LIBRO
CREATE TABLE LIBRO (
    ID_LIBRO INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(500) NULL,
    ANIO_PUBLICACION SMALLINT NULL, -- SMALLINT funciona, o puedes usar INT
    ID_AUTOR INT NULL,
    ID_GENERO INT NULL,
    PRIMARY KEY (ID_LIBRO),
    CONSTRAINT FK_LIBRO_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID_AUTOR) ON DELETE SET NULL,
    CONSTRAINT FK_LIBRO_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Tabla: INVENTARIO
CREATE TABLE INVENTARIO (
    ID_INVENTARIO INT NOT NULL AUTO_INCREMENT,
    ID_LIBRO INT NULL,
    CANTIDAD_STOCK INT NOT NULL DEFAULT 0,
    NOTAS VARCHAR(255) NULL,
    FECHA_ULTIMO_INVENTARIO DATE DEFAULT (CURRENT_DATE), -- Sintaxis MySQL 8.0+
    PRIMARY KEY (ID_INVENTARIO),
    CONSTRAINT FK_INVENTARIO_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID_LIBRO) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 3. INSERCIÓN DE DATOS

INSERT INTO GENERO (NOMBRE) VALUES 
('Ficción'), ('Ciencia Ficción'), ('Misterio'), ('Fantasía'), ('No Ficción');

INSERT INTO AUTOR (NOMBRE_COMPLETO, FECHA_NACIMIENTO, FECHA_FALLECIMIENTO) VALUES
('Gabriel García Márquez', '1927-03-06', '2014-04-17'),
('Leo Tolstoy', '1828-09-09', '1910-11-20'),
('George Orwell', '1903-06-25', '1950-01-21'),
('Haruki Murakami', '1949-01-12', NULL),
('Isabel Allende', '1942-08-02', NULL);

INSERT INTO LIBRO (TITULO, DESCRIPCION, ANIO_PUBLICACION, ID_AUTOR, ID_GENERO) VALUES
('Cien años de soledad', 'Una novela sobre la familia Buendía en Macondo.', 1967, 1, 1),
('Guerra y Paz', 'Épica sobre la invasión napoleónica a Rusia.', 1869, 2, 5),
('1984', 'Crítica a los regímenes totalitarios.', 1949, 3, 3),
('Kafka en la orilla', 'Un joven busca su destino.', 2002, 4, 4),
('La casa de los espíritus', 'Saga familiar con realismo mágico.', 1982, 5, 1);

INSERT INTO INVENTARIO (ID_LIBRO, CANTIDAD_STOCK, NOTAS) VALUES
(1, 30, 'En buen estado'),
(2, 50, 'Exitoso en ventas'),
(3, 20, 'Requiere reposición'),
(4, 15, 'Poco solicitado'),
(5, 25, 'Reedición reciente');

-- Mensaje de confirmación (Simulado con SELECT)
SELECT 'Base de datos LibreriaDB creada y cargada exitosamente en MySQL.' AS Mensaje;